name: flutter_hive_generator_fixed
description: "hive_generator fixed"
version: 0.0.3
homepage: https://github.com/angcyo/flutter_pub_generator_fixed
repository: https://github.com/angcyo/flutter_pub_generator_fixed
#publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  # https://pub.dev/packages/build_runner
  # https://pub.dev/packages/build
  # https://pub.dev/packages/build_config
  # https://pub.dev/packages/build_daemon
  # https://pub.dev/packages/build_runner_core
  # https://pub.dev/packages/code_builder
  # https://pub.dev/packages/dart_style
  # https://pub.dev/packages/pub_semver
  build_runner: ^2.7.0
  # https://pub.dev/packages/build
  # https://pub.dev/packages/build_runner_core
  build: ^3.0.2
  # https://pub.dev/packages/build_config
  #build_config: ^1.2.0

  # https://pub.dev/packages/source_gen
  # https://pub.dev/packages/build
  # https://pub.dev/packages/dart_style
  # https://pub.dev/packages/pub_semver
  source_gen: ^3.1.0
  # https://pub.dev/packages/source_helper
  source_helper: ^1.3.7

  # https://pub.dev/packages/analyzer
  # https://pub.dev/packages/pub_semver
  analyzer: ^8.1.1

  # https://pub.dev/packages/hive
  hive: ^2.2.3

dev_dependencies:
  # https://pub.dev/packages/build_test
  build_test: ^3.3.2
  # https://pub.dev/packages/test
  test: ^1.26.3