name: flutter_isar_generator_fixed
description: "isar_generator fixed"
version: 0.0.2
homepage: https://github.com/angcyo/flutter_pub_generator_fixed
repository: https://github.com/angcyo/flutter_pub_generator_fixed
#publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  # https://pub.dev/packages/build_runner
  # https://pub.dev/packages/build
  # https://pub.dev/packages/build_config
  # https://pub.dev/packages/build_daemon
  # https://pub.dev/packages/build_runner_core
  # https://pub.dev/packages/code_builder
  # https://pub.dev/packages/dart_style
  # https://pub.dev/packages/pub_semver
  build_runner: ^2.7.0
  # https://pub.dev/packages/build
  # https://pub.dev/packages/build_runner_core
  build: ^3.0.2
  # https://pub.dev/packages/build_config
  #build_config: ^1.2.0

  # https://pub.dev/packages/source_gen
  # https://pub.dev/packages/build
  # https://pub.dev/packages/dart_style
  # https://pub.dev/packages/pub_semver
  source_gen: ^3.1.0
  # https://pub.dev/packages/source_helper
  #source_helper: ^1.3.7

  # https://pub.dev/packages/analyzer
  # https://pub.dev/packages/pub_semver
  analyzer: ^8.1.1

  # https://pub.dev/packages/dart_style
  dart_style: ^3.1.2
  # https://pub.dev/packages/dartx
  dartx: ^1.2.0
  # https://pub.dev/packages/xxh3
  xxh3: ^1.2.0

  # https://pub.dev/packages/isar
  isar: ^3.1.0+1

dev_dependencies:
  # https://pub.dev/packages/build_test
  build_test: ^3.3.2
  # https://pub.dev/packages/test
  test: ^1.26.3