name: generator_example
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/angcyo/flutter_pub_generator_fixed
publish_to: none

environment:
  sdk: ^3.8.0

isar_version: &isar_version ^3.1.0+1

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/isar
  isar: *isar_version

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  # https://pub.dev/packages/hive
  hive: ^2.2.3

dependency_overrides:
  # https://pub.dev/packages/analyzer
  # https://pub.dev/packages/pub_semver
  #Because no versions of json_serializable match >6.10.0 <7.0.0 and json_serializable 6.10.0 depends on analyzer ^7.4.0, json_serializable ^6.10.0 requires analyzer ^7.4.0.
  #And because every version of flutter_isar_generator_fixed from path depends on analyzer ^8.1.1, json_serializable ^6.10.0 is incompatible with flutter_isar_generator_fixed from path.
  #So, because generator_example depends on both flutter_isar_generator_fixed from path and json_serializable ^6.10.0, version solving failed.
  analyzer: ^8.1.1

dev_dependencies:
  # https://pub.dev/packages/build_test
  build_test: ^3.3.2
  # https://pub.dev/packages/test
  test: ^1.26.3

  # https://pub.dev/packages/build_runner
  build_runner: any

  # test
  flutter_isar_generator_fixed:
    path: ../../packages/flutter_isar_generator_fixed

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.10.0

  # test
  flutter_hive_generator_fixed:
    path: ../../packages/flutter_hive_generator_fixed
